# Generated by Django 4.0.6 on 2022-08-28 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='applyjobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jbtitle', models.CharField(max_length=200, null=True)),
                ('jbplace', models.CharField(max_length=200, null=True)),
                ('jbdate', models.CharField(max_length=200, null=True)),
                ('jbname', models.CharField(max_length=200, null=True)),
                ('jbdes', models.CharField(max_length=200, null=True)),
                ('jbno', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='complaintjb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaintsub', models.CharField(max_length=200, null=True)),
                ('complaintdes', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='complaintworker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaintsub', models.CharField(max_length=200, null=True)),
                ('complaintdes', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='fitnessreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='insurance_scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policyno', models.CharField(max_length=200, null=True)),
                ('insurancetype', models.CharField(max_length=200, null=True)),
                ('company', models.CharField(max_length=200, null=True)),
                ('policyDescription', models.CharField(max_length=200, null=True)),
                ('timelength', models.CharField(max_length=200, null=True)),
                ('insuranceamount', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='insurance_scheme1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policyno', models.CharField(max_length=200, null=True)),
                ('insurancetype', models.CharField(max_length=200, null=True)),
                ('company', models.CharField(max_length=200, null=True)),
                ('policyDescription', models.CharField(max_length=200, null=True)),
                ('timelength', models.CharField(max_length=200, null=True)),
                ('insuranceamount', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='insuranceagency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('type1', models.CharField(max_length=200, null=True)),
                ('no', models.CharField(max_length=200, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('password2', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='jobprovider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('dob', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(max_length=200, null=True)),
                ('no', models.CharField(max_length=200, null=True)),
                ('photoid', models.FileField(upload_to='')),
                ('password', models.CharField(max_length=200, null=True)),
                ('password2', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jbtitle', models.CharField(max_length=200, null=True)),
                ('jbplace', models.CharField(max_length=200, null=True)),
                ('jbdate', models.CharField(max_length=200, null=True)),
                ('jbname', models.CharField(max_length=200, null=True)),
                ('jbdes', models.CharField(max_length=200, null=True)),
                ('jbno', models.CharField(max_length=200, null=True)),
                ('jbstatus', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='police',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eye', models.ImageField(upload_to='')),
                ('adhar', models.ImageField(upload_to='')),
                ('fitness', models.ImageField(upload_to='')),
                ('yesno', models.CharField(max_length=200)),
                ('approved', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('dob', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(max_length=200, null=True)),
                ('no', models.CharField(max_length=200, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('password2', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='additionalinfo1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place1', models.CharField(max_length=200, null=True)),
                ('address1', models.CharField(max_length=200, null=True)),
                ('address2', models.CharField(max_length=200, null=True)),
                ('wages1', models.CharField(max_length=200, null=True)),
                ('pan1', models.CharField(max_length=200, null=True)),
                ('gpay1', models.CharField(max_length=200, null=True)),
                ('photo1', models.CharField(max_length=200, null=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MWMapp.worker')),
            ],
        ),
    ]
