# Generated by Django 4.0.5 on 2022-08-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MWMapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='applyjobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jbtitle', models.CharField(max_length=200, null=True)),
                ('jbplace', models.CharField(max_length=200, null=True)),
                ('jbdate', models.CharField(max_length=200, null=True)),
                ('jbname', models.CharField(max_length=200, null=True)),
                ('jbdes', models.CharField(max_length=200, null=True)),
                ('jbno', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
