# Generated by Django 4.0.6 on 2022-08-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MWMapp', '0002_alter_product_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
