# Generated by Django 4.0.5 on 2022-08-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MWMapp', '0002_insurance_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance_scheme',
            name='company',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='insurance_scheme',
            name='insurancetype',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='insurance_scheme',
            name='insurnaceamount',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='insurance_scheme',
            name='policyDescription',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='insurance_scheme',
            name='policyno',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='insurance_scheme',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='insurance_scheme',
            name='timelength',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
