# Generated by Django 4.0.5 on 2022-08-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MWMapp', '0002_applyjobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='insurance_scheme1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policyno', models.CharField(max_length=200, null=True)),
                ('insurancetype', models.CharField(max_length=200, null=True)),
                ('company', models.CharField(max_length=200, null=True)),
                ('policyDescription', models.CharField(max_length=200, null=True)),
                ('timelength', models.CharField(max_length=200, null=True)),
                ('insuranceamount', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
