# Generated by Django 4.0.5 on 2022-08-23 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MWMapp', '0003_insurance_scheme_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance_scheme',
            name='add_scheme',
        ),
        migrations.RemoveField(
            model_name='insurance_scheme',
            name='name',
        ),
    ]
