# Generated by Django 4.0.5 on 2022-08-23 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MWMapp', '0004_remove_insurance_scheme_add_scheme_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurance_scheme',
            old_name='insurnaceamount',
            new_name='insuranceamount',
        ),
    ]
