# Generated by Django 4.0.5 on 2022-08-23 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MWMapp', '0005_rename_insurnaceamount_insurance_scheme_insuranceamount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance_scheme',
            name='status',
        ),
    ]
